const compiled = {};
compiled['bbs'] = function anonymous(__this,body,formMsg,include,name,pager,posts,title,wrapper
) {
try {/*+*/__this.ret+='<!--meta.keys=["title", "name", "body", "formMsg", "posts", "pager"]-->';
__this.line=2;__this.ret+='\n';/* */ __this.stash.title = 'BBS'; ;/*+*/__this.ret+='';
__this.line=3;__this.ret+='\n';/* */ wrapper('wrapper', () => { ;/*+*/__this.ret+='';
__this.line=4;__this.ret+='\n  <h1><a href="/bbs">掲示板</a></h1>';
__this.line=5;__this.ret+='\n  <div class="bbs-form">';
__this.line=6;__this.ret+='\n    <form id="postForm" method="post" action="/bbs/post">';
__this.line=7;__this.ret+='\n      <label>おなまえ <input name="name" maxlength="20" required value="';/*=*/__this.ret+=__this.escapeHTML( name || '' );/*+*/__this.ret+='"></label>';
__this.line=8;__this.ret+='\n      <label>本文 <br><textarea name="body" maxlength="300" required>';/*=*/__this.ret+=__this.escapeHTML( body || '' );/*+*/__this.ret+='</textarea></label>';
__this.line=9;__this.ret+='\n      <label>削除キー（任意）<input name="deleteKey" maxlength="32" type="password" autocomplete="off"></label>';
__this.line=10;__this.ret+='\n      <button type="submit">書き込む</button>';
__this.line=11;__this.ret+='\n    </form>';
__this.line=12;__this.ret+='\n    <div id="formMsg"></div>';
__this.line=13;__this.ret+='\n  </div>';
__this.line=14;__this.ret+='\n  <div class="bbs-list" id="bbsList">';
__this.line=15;__this.ret+='\n    ';/* */ if (posts.length === 0) { ;/*+*/__this.ret+='';
__this.line=16;__this.ret+='\n      <div>まだ投稿はありません</div>';
__this.line=17;__this.ret+='\n    ';/* */ } else { ;/*+*/__this.ret+='';
__this.line=18;__this.ret+='\n      ';/* */ posts.forEach(function(post) { ;/*+*/__this.ret+='';
__this.line=19;__this.ret+='\n        <div class="bbs-post" data-id="';/*=*/__this.ret+=__this.escapeHTML( post.id );/*+*/__this.ret+='">';
__this.line=20;__this.ret+='\n          <div class="bbs-meta">';/*=*/__this.ret+=__this.escapeHTML( post.name );/*+*/__this.ret+=' さん ';
__this.line=21;__this.ret+='\n			<time datetime="';/*=*/__this.ret+=__this.escapeHTML( post.date );/*+*/__this.ret+='">';/*=*/__this.ret+=__this.escapeHTML( post.date );/*+*/__this.ret+='</time>';
__this.line=22;__this.ret+='\n			 <span style="font-size:0.8em;color:#aaa;">[';/*=*/__this.ret+=__this.escapeHTML( post.ipHash ? 'ID:' + post.ipHash : '' );/*+*/__this.ret+=']</span></div>';
__this.line=23;__this.ret+='\n          <div class="bbs-body">';/*=*/__this.ret+=__this.escapeHTML( post.body );/*+*/__this.ret+='</div>';
__this.line=24;__this.ret+='\n          ';/* */ if (post.deleteKey) { ;/*+*/__this.ret+='';
__this.line=25;__this.ret+='\n			<form class="bbs-delete-form" method="post" action="/bbs/delete" style="display:inline;">';
__this.line=26;__this.ret+='\n				<input type="password" name="deleteKey" placeholder="削除キー" maxlength="32" autocomplete="off" required>';
__this.line=27;__this.ret+='\n				<input type="hidden" name="id" value="';/*=*/__this.ret+=__this.escapeHTML( post.id );/*+*/__this.ret+='"><button class="bbs-delete" title="削除">削除</button>';
__this.line=28;__this.ret+='\n			</form>';
__this.line=29;__this.ret+='\n		  ';/* */ } ;/*+*/__this.ret+='';
__this.line=30;__this.ret+='\n        </div>';
__this.line=31;__this.ret+='\n      ';/* */ }); ;/*+*/__this.ret+='';
__this.line=32;__this.ret+='\n    ';/* */ } ;/*+*/__this.ret+='';
__this.line=33;__this.ret+='\n  </div>';
__this.line=34;__this.ret+='\n  <div id="bbsPaging" style="margin:1em 0;">';
__this.line=35;__this.ret+='\n    ';/* */ if (pager.total > 0) { ;/*+*/__this.ret+='';
__this.line=36;__this.ret+='\n      <form method="get" action="/bbs" style="display:inline;">';
__this.line=37;__this.ret+='\n        <button name="offset" value="';/*=*/__this.ret+=__this.escapeHTML( Math.max(pager.offset - pager.limit, 0) );/*+*/__this.ret+='" ';/*=*/__this.ret+=__this.escapeHTML( pager.offset === 0 ? 'disabled' : '' );/*+*/__this.ret+='>次へ</button>';
__this.line=38;__this.ret+='\n      </form>';
__this.line=39;__this.ret+='\n      <span style="margin:0 1em;">';/*=*/__this.ret+=__this.escapeHTML( Math.max(pager.total - pager.offset - pager.limit + 1, 1) );/*+*/__this.ret+='～';/*=*/__this.ret+=__this.escapeHTML( pager.total - pager.offset );/*+*/__this.ret+=' 件目 / 全';/*=*/__this.ret+=__this.escapeHTML( pager.total );/*+*/__this.ret+='件</span>';
__this.line=40;__this.ret+='\n      <form method="get" action="/bbs" style="display:inline;">';
__this.line=41;__this.ret+='\n        <button name="offset" value="';/*=*/__this.ret+=__this.escapeHTML( pager.offset + pager.limit );/*+*/__this.ret+='" ';/*=*/__this.ret+=__this.escapeHTML( pager.offset + pager.limit >= pager.total ? 'disabled' : '' );/*+*/__this.ret+='>前へ</button>';
__this.line=42;__this.ret+='\n      </form>';
__this.line=43;__this.ret+='\n    ';/* */ } ;/*+*/__this.ret+='';
__this.line=44;__this.ret+='\n  </div>';
__this.line=45;__this.ret+='\n  <script>';
__this.line=46;__this.ret+='\n    document.addEventListener(\'DOMContentLoaded\', function() {';
__this.line=47;__this.ret+='\n      document.querySelectorAll(\'form[method="post"]\').forEach(function(form) {';
__this.line=48;__this.ret+='\n        form.addEventListener(\'submit\', async function(e) {';
__this.line=49;__this.ret+='\n          e.preventDefault();';
__this.line=50;__this.ret+='\n          const formData = new FormData(form);';
__this.line=51;__this.ret+='\n          const data = {};';
__this.line=52;__this.ret+='\n          formData.forEach((v, k) => { data[k] = v; });';
__this.line=53;__this.ret+='\n          const res = await fetch(form.action, {';
__this.line=54;__this.ret+='\n            method: \'POST\',';
__this.line=55;__this.ret+='\n            headers: {';
__this.line=56;__this.ret+='\n              \'Content-Type\': \'application/json\',';
__this.line=57;__this.ret+='\n              \'X-Requested-With\': \'XMLHttpRequest\'';
__this.line=58;__this.ret+='\n            },';
__this.line=59;__this.ret+='\n            body: JSON.stringify(data)';
__this.line=60;__this.ret+='\n          });';
__this.line=61;__this.ret+='\n          if (form.id === \'postForm\') {';
__this.line=62;__this.ret+='\n            const msg = document.getElementById(\'formMsg\');';
__this.line=63;__this.ret+='\n            if (!res.ok) {';
__this.line=64;__this.ret+='\n              msg.textContent = await res.text();';
__this.line=65;__this.ret+='\n              msg.className = \'bbs-error\';';
__this.line=66;__this.ret+='\n            } else {';
__this.line=67;__this.ret+='\n              msg.textContent = \'書き込み完了！\';';
__this.line=68;__this.ret+='\n              msg.className = \'bbs-success\';';
__this.line=69;__this.ret+='\n              form.reset();';
__this.line=70;__this.ret+='\n              location.reload();';
__this.line=71;__this.ret+='\n            }';
__this.line=72;__this.ret+='\n          } else if (form.classList.contains(\'bbs-delete-form\')) {';
__this.line=73;__this.ret+='\n            if (res.ok) {';
__this.line=74;__this.ret+='\n              location.reload();';
__this.line=75;__this.ret+='\n            } else {';
__this.line=76;__this.ret+='\n              alert(await res.text());';
__this.line=77;__this.ret+='\n            }';
__this.line=78;__this.ret+='\n          }';
__this.line=79;__this.ret+='\n        });';
__this.line=80;__this.ret+='\n      });';
__this.line=81;__this.ret+='\n    });';
__this.line=82;__this.ret+='\n  </script>';
__this.line=83;__this.ret+='\n';/* */ }); /* end of wrapper */ ;/*end*/ return __this.ret;} catch (e) { throw new Error('TemplateError: '+e+' (on bbs line ' + __this.line + ')',{cause:e}); }

};
compiled['bbs'].keys = ["body","formMsg","include","name","pager","posts","title","wrapper"];
compiled['wrapper'] = function anonymous(__this,content,include,title,wrapper
) {
try {/*+*/__this.ret+='<!--meta.keys=["title", "content"]-->';
__this.line=2;__this.ret+='\n<!DOCTYPE html>';
__this.line=3;__this.ret+='\n<html>';
__this.line=4;__this.ret+='\n<head>';
__this.line=5;__this.ret+='\n	<meta charset="UTF-8">';
__this.line=6;__this.ret+='\n	<meta name="viewport" content="width=device-width, initial-scale=1.0">';
__this.line=7;__this.ret+='\n	<title>';/*=*/__this.ret+=__this.escapeHTML( title );/*+*/__this.ret+='</title>';
__this.line=8;__this.ret+='\n  <style>';
__this.line=9;__this.ret+='\n    body {';
__this.line=10;__this.ret+='\n      font-family: \'MS PGothic\', \'Osaka\', \'Arial\', sans-serif;';
__this.line=11;__this.ret+='\n      background: #fffbe7;';
__this.line=12;__this.ret+='\n      color: #222;';
__this.line=13;__this.ret+='\n      text-align: center;';
__this.line=14;__this.ret+='\n      margin-top: 2em;';
__this.line=15;__this.ret+='\n    }';
__this.line=16;__this.ret+='\n    h1 {';
__this.line=17;__this.ret+='\n      font-size: 2em;';
__this.line=18;__this.ret+='\n      color: #0066cc;';
__this.line=19;__this.ret+='\n      text-shadow: 1px 1px 0 #fff, 2px 2px 0 #bde6ff;';
__this.line=20;__this.ret+='\n      border-bottom: 3px double #0099cc;';
__this.line=21;__this.ret+='\n      display: block;';
__this.line=22;__this.ret+='\n      padding: 0.2em 1em 0.1em 1em;';
__this.line=23;__this.ret+='\n      background: #fff;';
__this.line=24;__this.ret+='\n      border-radius: 8px 8px 0 0;';
__this.line=25;__this.ret+='\n      margin: 0 auto 1em auto;';
__this.line=26;__this.ret+='\n      width: fit-content;';
__this.line=27;__this.ret+='\n    }';
__this.line=28;__this.ret+='\n    .bbs-form {';
__this.line=29;__this.ret+='\n      background: #e0f7fa;';
__this.line=30;__this.ret+='\n      border: 2px solid #b2ebf2;';
__this.line=31;__this.ret+='\n      border-radius: 8px;';
__this.line=32;__this.ret+='\n      display: block;';
__this.line=33;__this.ret+='\n      padding: 1em 2em;';
__this.line=34;__this.ret+='\n      margin: 0 auto 2em auto;';
__this.line=35;__this.ret+='\n      box-shadow: 2px 2px 0 #ccc;';
__this.line=36;__this.ret+='\n      max-width: 500px;';
__this.line=37;__this.ret+='\n    }';
__this.line=38;__this.ret+='\n    .bbs-form input, .bbs-form textarea {';
__this.line=39;__this.ret+='\n      font-family: inherit;';
__this.line=40;__this.ret+='\n      font-size: 1em;';
__this.line=41;__this.ret+='\n      margin: 0.2em 0;';
__this.line=42;__this.ret+='\n      border: 1px solid #bbb;';
__this.line=43;__this.ret+='\n      border-radius: 4px;';
__this.line=44;__this.ret+='\n      padding: 0.3em 0.5em;';
__this.line=45;__this.ret+='\n      width: 90%;';
__this.line=46;__this.ret+='\n      box-sizing: border-box;';
__this.line=47;__this.ret+='\n    }';
__this.line=48;__this.ret+='\n    .bbs-form textarea {';
__this.line=49;__this.ret+='\n      min-height: 4em;';
__this.line=50;__this.ret+='\n      resize: vertical;';
__this.line=51;__this.ret+='\n    }';
__this.line=52;__this.ret+='\n    .bbs-form label {';
__this.line=53;__this.ret+='\n      display: block;';
__this.line=54;__this.ret+='\n      margin-top: 0.5em;';
__this.line=55;__this.ret+='\n      text-align: left;';
__this.line=56;__this.ret+='\n    }';
__this.line=57;__this.ret+='\n    .bbs-form button {';
__this.line=58;__this.ret+='\n      margin-top: 1em;';
__this.line=59;__this.ret+='\n      padding: 0.5em 2em;';
__this.line=60;__this.ret+='\n      font-size: 1em;';
__this.line=61;__this.ret+='\n      background: #fffbe7;';
__this.line=62;__this.ret+='\n      border: 1px solid #aaa;';
__this.line=63;__this.ret+='\n      border-radius: 4px;';
__this.line=64;__this.ret+='\n      cursor: pointer;';
__this.line=65;__this.ret+='\n    }';
__this.line=66;__this.ret+='\n    .bbs-list {';
__this.line=67;__this.ret+='\n      margin: 2em auto 0 auto;';
__this.line=68;__this.ret+='\n      max-width: 600px;';
__this.line=69;__this.ret+='\n      text-align: left;';
__this.line=70;__this.ret+='\n      display: block;';
__this.line=71;__this.ret+='\n    }';
__this.line=72;__this.ret+='\n    .bbs-post {';
__this.line=73;__this.ret+='\n      background: #fff;';
__this.line=74;__this.ret+='\n      border: 1px solid #ccc;';
__this.line=75;__this.ret+='\n      border-radius: 6px;';
__this.line=76;__this.ret+='\n      margin-bottom: 1.2em;';
__this.line=77;__this.ret+='\n      padding: 0.8em 1em;';
__this.line=78;__this.ret+='\n      box-shadow: 1px 1px 0 #eee;';
__this.line=79;__this.ret+='\n      position: static;';
__this.line=80;__this.ret+='\n      display: block;';
__this.line=81;__this.ret+='\n    }';
__this.line=82;__this.ret+='\n    .bbs-post .bbs-meta {';
__this.line=83;__this.ret+='\n      font-size: 0.9em;';
__this.line=84;__this.ret+='\n      color: #888;';
__this.line=85;__this.ret+='\n      margin-bottom: 0.3em;';
__this.line=86;__this.ret+='\n      display: block;';
__this.line=87;__this.ret+='\n    }';
__this.line=88;__this.ret+='\n    .bbs-post .bbs-body {';
__this.line=89;__this.ret+='\n      white-space: pre-wrap;';
__this.line=90;__this.ret+='\n      word-break: break-all;';
__this.line=91;__this.ret+='\n      margin-bottom: 0.5em;';
__this.line=92;__this.ret+='\n      display: block;';
__this.line=93;__this.ret+='\n    }';
__this.line=94;__this.ret+='\n    .bbs-post .bbs-delete {';
__this.line=95;__this.ret+='\n      font-size: 0.9em;';
__this.line=96;__this.ret+='\n      color: #c00;';
__this.line=97;__this.ret+='\n      background: none;';
__this.line=98;__this.ret+='\n      border: none;';
__this.line=99;__this.ret+='\n      cursor: pointer;';
__this.line=100;__this.ret+='\n      text-decoration: underline;';
__this.line=101;__this.ret+='\n      display: inline;';
__this.line=102;__this.ret+='\n      position: static;';
__this.line=103;__this.ret+='\n      float: none;';
__this.line=104;__this.ret+='\n    }';
__this.line=105;__this.ret+='\n    .bbs-error, .bbs-success {';
__this.line=106;__this.ret+='\n      display: block;';
__this.line=107;__this.ret+='\n      margin: 1em 0;';
__this.line=108;__this.ret+='\n    }';
__this.line=109;__this.ret+='\n  </style>';
__this.line=110;__this.ret+='\n</head>';
__this.line=111;__this.ret+='\n<body>';
__this.line=112;__this.ret+='\n	<a href="/">トップページ</a> | <a href="/bbs">掲示板</a> | <a href="/diary">日記</a>';
__this.line=113;__this.ret+='\n	';/*raw*/__this.ret+=( content );/*+*/__this.ret+='';
__this.line=114;__this.ret+='\n</body>';
__this.line=115;__this.ret+='\n</html>';/*end*/ return __this.ret;} catch (e) { throw new Error('TemplateError: '+e+' (on wrapper line ' + __this.line + ')',{cause:e}); }

};
compiled['wrapper'].keys = ["content","include","title","wrapper"];
compiled['diary/archive-month'] = function anonymous(__this,entries,formatDateForDisplay,formatDateOnly,include,month,nl2br,title,wrapper,year
) {
try {/*+*/__this.ret+='<!--meta.keys=["title", "year", "month", "entries", "formatDateOnly", "formatDateForDisplay", "nl2br"]-->';
__this.line=2;__this.ret+='\n';/* */ __this.stash.title = year + '年' + month + '月 - 日記アーカイブ'; ;/*+*/__this.ret+='';
__this.line=3;__this.ret+='\n';/* */ wrapper('wrapper', () => { ;/*+*/__this.ret+='';
__this.line=4;__this.ret+='\n    <style>';
__this.line=5;__this.ret+='\n        .diary-nav { margin: 20px 0; }';
__this.line=6;__this.ret+='\n        .diary-nav a { margin-right: 15px; color: #0066cc; text-decoration: none; }';
__this.line=7;__this.ret+='\n        .diary-nav a:hover { text-decoration: underline; }';
__this.line=8;__this.ret+='\n        .diary-entry { margin-bottom: 30px; border-bottom: 1px dotted #ccc; padding-bottom: 20px; }';
__this.line=9;__this.ret+='\n        .diary-entry-date { font-weight: bold; color: #333; margin-bottom: 10px; }';
__this.line=10;__this.ret+='\n        .diary-entry-date a { color: #333; text-decoration: none; }';
__this.line=11;__this.ret+='\n        .diary-entry-date a:hover { text-decoration: underline; }';
__this.line=12;__this.ret+='\n        .diary-entry-body { white-space: pre-wrap; line-height: 1.6; }';
__this.line=13;__this.ret+='\n        .diary-entry-meta { font-size: 0.9em; color: #666; margin-top: 10px; }';
__this.line=14;__this.ret+='\n        .diary-admin-links { margin-top: 10px; }';
__this.line=15;__this.ret+='\n        .diary-admin-links a { margin-right: 10px; font-size: 0.9em; color: #0066cc; }';
__this.line=16;__this.ret+='\n        .diary-no-entries { text-align: center; color: #999; margin: 40px 0; }';
__this.line=17;__this.ret+='\n    </style>';
__this.line=18;__this.ret+='\n';
__this.line=19;__this.ret+='\n    <h1>';/*=*/__this.ret+=__this.escapeHTML( year );/*+*/__this.ret+='年';/*=*/__this.ret+=__this.escapeHTML( month );/*+*/__this.ret+='月 日記アーカイブ</h1>';
__this.line=20;__this.ret+='\n    ';
__this.line=21;__this.ret+='\n    <div class="diary-nav">';
__this.line=22;__this.ret+='\n        <a href="/diary">最新日記</a>';
__this.line=23;__this.ret+='\n        <a href="/diary/year/';/*=*/__this.ret+=__this.escapeHTML( year );/*+*/__this.ret+='">';/*=*/__this.ret+=__this.escapeHTML( year );/*+*/__this.ret+='年一覧</a>';
__this.line=24;__this.ret+='\n    </div>';
__this.line=25;__this.ret+='\n';
__this.line=26;__this.ret+='\n    ';/* */ if (entries && entries.length > 0) { ;/*+*/__this.ret+='';
__this.line=27;__this.ret+='\n        ';/* */ entries.forEach(function(entry) { ;/*+*/__this.ret+='';
__this.line=28;__this.ret+='\n            <div class="diary-entry">';
__this.line=29;__this.ret+='\n                <div class="diary-entry-date">';
__this.line=30;__this.ret+='\n                    <a href="/diary/';/*=*/__this.ret+=__this.escapeHTML( entry.id );/*+*/__this.ret+='">';/*=*/__this.ret+=__this.escapeHTML( formatDateOnly(entry.id) );/*+*/__this.ret+='</a>';
__this.line=31;__this.ret+='\n                </div>';
__this.line=32;__this.ret+='\n                <div class="diary-entry-body">';/*raw*/__this.ret+=( nl2br(entry.body) );/*+*/__this.ret+='</div>';
__this.line=33;__this.ret+='\n                <div class="diary-entry-meta">';
__this.line=34;__this.ret+='\n                    作成: ';/*=*/__this.ret+=__this.escapeHTML( formatDateForDisplay(entry.createdAt) );/*+*/__this.ret+='';
__this.line=35;__this.ret+='\n                    ';/* */ if (entry.updatedAt !== entry.createdAt) { ;/*+*/__this.ret+='';
__this.line=36;__this.ret+='\n                        / 更新: ';/*=*/__this.ret+=__this.escapeHTML( formatDateForDisplay(entry.updatedAt) );/*+*/__this.ret+='';
__this.line=37;__this.ret+='\n                    ';/* */ } ;/*+*/__this.ret+='';
__this.line=38;__this.ret+='\n                </div>';
__this.line=39;__this.ret+='\n            </div>';
__this.line=40;__this.ret+='\n        ';/* */ }); ;/*+*/__this.ret+='';
__this.line=41;__this.ret+='\n    ';/* */ } else { ;/*+*/__this.ret+='';
__this.line=42;__this.ret+='\n        <div class="diary-no-entries">';/*=*/__this.ret+=__this.escapeHTML( year );/*+*/__this.ret+='年';/*=*/__this.ret+=__this.escapeHTML( month );/*+*/__this.ret+='月には日記がありません。</div>';
__this.line=43;__this.ret+='\n    ';/* */ } ;/*+*/__this.ret+='';
__this.line=44;__this.ret+='\n';/* */ }); /* end of wrapper */ ;/*end*/ return __this.ret;} catch (e) { throw new Error('TemplateError: '+e+' (on diary/archive-month line ' + __this.line + ')',{cause:e}); }

};
compiled['diary/archive-month'].keys = ["entries","formatDateForDisplay","formatDateOnly","include","month","nl2br","title","wrapper","year"];
compiled['diary/archive-year'] = function anonymous(__this,allYears,include,months,title,wrapper,year
) {
try {/*+*/__this.ret+='<!--meta.keys=["title", "year", "months", "allYears"]-->';
__this.line=2;__this.ret+='\n';/* */ __this.stash.title = year + '年 - 日記アーカイブ'; ;/*+*/__this.ret+='';
__this.line=3;__this.ret+='\n';/* */ wrapper('wrapper', () => { ;/*+*/__this.ret+='';
__this.line=4;__this.ret+='\n    <style>';
__this.line=5;__this.ret+='\n        .diary-nav { margin: 20px 0; }';
__this.line=6;__this.ret+='\n        .diary-nav a { margin-right: 15px; color: #0066cc; text-decoration: none; }';
__this.line=7;__this.ret+='\n        .diary-nav a:hover { text-decoration: underline; }';
__this.line=8;__this.ret+='\n        .diary-month-list { display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); gap: 10px; margin: 20px 0; }';
__this.line=9;__this.ret+='\n        .diary-month-link { display: block; padding: 10px; text-align: center; border: 1px solid #ddd; color: #0066cc; text-decoration: none; }';
__this.line=10;__this.ret+='\n        .diary-month-link:hover { background-color: #f5f5f5; }';
__this.line=11;__this.ret+='\n    </style>';
__this.line=12;__this.ret+='\n';
__this.line=13;__this.ret+='\n    <h1>';/*=*/__this.ret+=__this.escapeHTML( year );/*+*/__this.ret+='年 日記アーカイブ</h1>';
__this.line=14;__this.ret+='\n    ';
__this.line=15;__this.ret+='\n    <div class="diary-nav">';
__this.line=16;__this.ret+='\n        <a href="/diary">最新日記</a>';
__this.line=17;__this.ret+='\n        ';/* */ if (allYears && allYears.length > 0) { ;/*+*/__this.ret+='';
__this.line=18;__this.ret+='\n            ';/* */ allYears.forEach(function(y) { ;/*+*/__this.ret+='';
__this.line=19;__this.ret+='\n                ';/* */ if (y !== year) { ;/*+*/__this.ret+='';
__this.line=20;__this.ret+='\n                    <a href="/diary/year/';/*=*/__this.ret+=__this.escapeHTML( y );/*+*/__this.ret+='">';/*=*/__this.ret+=__this.escapeHTML( y );/*+*/__this.ret+='年</a>';
__this.line=21;__this.ret+='\n                ';/* */ } ;/*+*/__this.ret+='';
__this.line=22;__this.ret+='\n            ';/* */ }); ;/*+*/__this.ret+='';
__this.line=23;__this.ret+='\n        ';/* */ } ;/*+*/__this.ret+='';
__this.line=24;__this.ret+='\n    </div>';
__this.line=25;__this.ret+='\n';
__this.line=26;__this.ret+='\n    ';/* */ if (months && months.length > 0) { ;/*+*/__this.ret+='';
__this.line=27;__this.ret+='\n        <div class="diary-month-list">';
__this.line=28;__this.ret+='\n            ';/* */ months.forEach(function(month) { ;/*+*/__this.ret+='';
__this.line=29;__this.ret+='\n                <a href="/diary/year/';/*=*/__this.ret+=__this.escapeHTML( year );/*+*/__this.ret+='/month/';/*=*/__this.ret+=__this.escapeHTML( month );/*+*/__this.ret+='" class="diary-month-link">';
__this.line=30;__this.ret+='\n                    ';/*=*/__this.ret+=__this.escapeHTML( month );/*+*/__this.ret+='月';
__this.line=31;__this.ret+='\n                </a>';
__this.line=32;__this.ret+='\n            ';/* */ }); ;/*+*/__this.ret+='';
__this.line=33;__this.ret+='\n        </div>';
__this.line=34;__this.ret+='\n    ';/* */ } else { ;/*+*/__this.ret+='';
__this.line=35;__this.ret+='\n        <p>';/*=*/__this.ret+=__this.escapeHTML( year );/*+*/__this.ret+='年には日記がありません。</p>';
__this.line=36;__this.ret+='\n    ';/* */ } ;/*+*/__this.ret+='';
__this.line=37;__this.ret+='\n';/* */ }); /* end of wrapper */ ;/*end*/ return __this.ret;} catch (e) { throw new Error('TemplateError: '+e+' (on diary/archive-year line ' + __this.line + ')',{cause:e}); }

};
compiled['diary/archive-year'].keys = ["allYears","include","months","title","wrapper","year"];
compiled['diary/detail'] = function anonymous(__this,entry,formatDateForDisplay,formatDateOnly,include,nl2br,title,wrapper
) {
try {/*+*/__this.ret+='<!--meta.keys=["title", "entry", "formatDateOnly", "formatDateForDisplay", "nl2br"]-->';
__this.line=2;__this.ret+='\n';/* */ __this.stash.title = formatDateOnly(entry.id) + ' - 日記'; ;/*+*/__this.ret+='';
__this.line=3;__this.ret+='\n';/* */ wrapper('wrapper', () => { ;/*+*/__this.ret+='';
__this.line=4;__this.ret+='\n    <style>';
__this.line=5;__this.ret+='\n        .diary-nav { margin: 20px 0; }';
__this.line=6;__this.ret+='\n        .diary-nav a { margin-right: 15px; color: #0066cc; text-decoration: none; }';
__this.line=7;__this.ret+='\n        .diary-nav a:hover { text-decoration: underline; }';
__this.line=8;__this.ret+='\n        .diary-detail { margin-bottom: 30px; }';
__this.line=9;__this.ret+='\n        .diary-detail-date { font-weight: bold; color: #333; margin-bottom: 10px; font-size: 1.2em; }';
__this.line=10;__this.ret+='\n        .diary-detail-body { white-space: pre-wrap; margin-bottom: 20px; line-height: 1.6; }';
__this.line=11;__this.ret+='\n        .diary-detail-meta { font-size: 0.9em; color: #666; margin-bottom: 20px; }';
__this.line=12;__this.ret+='\n        .diary-admin-links a { margin-right: 10px; color: #0066cc; }';
__this.line=13;__this.ret+='\n    </style>';
__this.line=14;__this.ret+='\n';
__this.line=15;__this.ret+='\n    <h1><a href="/diary">日記</a></h1>';
__this.line=16;__this.ret+='\n    ';
__this.line=17;__this.ret+='\n    <div class="diary-nav">';
__this.line=18;__this.ret+='\n        <a href="/diary">一覧に戻る</a>';
__this.line=19;__this.ret+='\n        <a href="/diary/new">新規投稿</a>';
__this.line=20;__this.ret+='\n    </div>';
__this.line=21;__this.ret+='\n';
__this.line=22;__this.ret+='\n    <div class="diary-detail">';
__this.line=23;__this.ret+='\n        <div class="diary-detail-date">';/*=*/__this.ret+=__this.escapeHTML( formatDateOnly(entry.id) );/*+*/__this.ret+='</div>';
__this.line=24;__this.ret+='\n        <div class="diary-detail-body">';/*raw*/__this.ret+=( nl2br(entry.body) );/*+*/__this.ret+='</div>';
__this.line=25;__this.ret+='\n        <div class="diary-detail-meta">';
__this.line=26;__this.ret+='\n            作成: ';/*=*/__this.ret+=__this.escapeHTML( formatDateForDisplay(entry.createdAt) );/*+*/__this.ret+='';
__this.line=27;__this.ret+='\n            ';/* */ if (entry.updatedAt !== entry.createdAt) { ;/*+*/__this.ret+='';
__this.line=28;__this.ret+='\n                <br>更新: ';/*=*/__this.ret+=__this.escapeHTML( formatDateForDisplay(entry.updatedAt) );/*+*/__this.ret+='';
__this.line=29;__this.ret+='\n            ';/* */ } ;/*+*/__this.ret+='';
__this.line=30;__this.ret+='\n        </div>';
__this.line=31;__this.ret+='\n        <div class="diary-admin-links">';
__this.line=32;__this.ret+='\n            <a href="/diary/';/*=*/__this.ret+=__this.escapeHTML( entry.id );/*+*/__this.ret+='/edit">編集</a>';
__this.line=33;__this.ret+='\n        </div>';
__this.line=34;__this.ret+='\n    </div>';
__this.line=35;__this.ret+='\n';/* */ }); /* end of wrapper */ ;/*end*/ return __this.ret;} catch (e) { throw new Error('TemplateError: '+e+' (on diary/detail line ' + __this.line + ')',{cause:e}); }

};
compiled['diary/detail'].keys = ["entry","formatDateForDisplay","formatDateOnly","include","nl2br","title","wrapper"];
compiled['diary/form'] = function anonymous(__this,body,date,entry,error,include,isEdit,title,wrapper
) {
try {/*+*/__this.ret+='<!--meta.keys=["title", "isEdit", "entry", "date", "body", "error"]-->';
__this.line=2;__this.ret+='\n';/* */ __this.stash.title = (isEdit ? '編集' : '新規投稿') + ' - 日記'; ;/*+*/__this.ret+='';
__this.line=3;__this.ret+='\n';/* */ wrapper('wrapper', () => { ;/*+*/__this.ret+='';
__this.line=4;__this.ret+='\n    <style>';
__this.line=5;__this.ret+='\n        .diary-nav { margin: 20px 0; }';
__this.line=6;__this.ret+='\n        .diary-nav a { margin-right: 15px; color: #0066cc; text-decoration: none; }';
__this.line=7;__this.ret+='\n        .diary-nav a:hover { text-decoration: underline; }';
__this.line=8;__this.ret+='\n        .diary-form-group { margin-bottom: 15px; }';
__this.line=9;__this.ret+='\n        .diary-form-group label { display: block; margin-bottom: 5px; font-weight: bold; }';
__this.line=10;__this.ret+='\n        .diary-form-group input[type="date"] { padding: 5px; font-size: 14px; }';
__this.line=11;__this.ret+='\n        .diary-form-group textarea { width: 100%; height: 300px; padding: 10px; font-family: serif; font-size: 14px; box-sizing: border-box; }';
__this.line=12;__this.ret+='\n        .diary-form-buttons { margin-top: 20px; }';
__this.line=13;__this.ret+='\n        .diary-form-buttons button { padding: 10px 20px; margin-right: 10px; font-size: 14px; }';
__this.line=14;__this.ret+='\n        .diary-error { color: red; margin-bottom: 15px; }';
__this.line=15;__this.ret+='\n    </style>';
__this.line=16;__this.ret+='\n';
__this.line=17;__this.ret+='\n    <h1>日記 - ';/*=*/__this.ret+=__this.escapeHTML( isEdit ? '編集' : '新規投稿' );/*+*/__this.ret+='</h1>';
__this.line=18;__this.ret+='\n    ';
__this.line=19;__this.ret+='\n    <div class="diary-nav">';
__this.line=20;__this.ret+='\n        <a href="/diary">一覧に戻る</a>';
__this.line=21;__this.ret+='\n        ';/* */ if (isEdit && entry) { ;/*+*/__this.ret+='';
__this.line=22;__this.ret+='\n            <a href="/diary/';/*=*/__this.ret+=__this.escapeHTML( entry.id );/*+*/__this.ret+='">詳細に戻る</a>';
__this.line=23;__this.ret+='\n        ';/* */ } ;/*+*/__this.ret+='';
__this.line=24;__this.ret+='\n    </div>';
__this.line=25;__this.ret+='\n';
__this.line=26;__this.ret+='\n    ';/* */ if (error) { ;/*+*/__this.ret+='';
__this.line=27;__this.ret+='\n        <div class="diary-error">';/*=*/__this.ret+=__this.escapeHTML( error );/*+*/__this.ret+='</div>';
__this.line=28;__this.ret+='\n    ';/* */ } ;/*+*/__this.ret+='';
__this.line=29;__this.ret+='\n';
__this.line=30;__this.ret+='\n    <form method="POST" action="';/*=*/__this.ret+=__this.escapeHTML( isEdit ? '/diary/' + entry.id + '/edit' : '/diary' );/*+*/__this.ret+='">';
__this.line=31;__this.ret+='\n        <div class="diary-form-group">';
__this.line=32;__this.ret+='\n            <label for="date">日付:</label>';
__this.line=33;__this.ret+='\n            <input type="date" id="date" name="date" value="';/*=*/__this.ret+=__this.escapeHTML( date );/*+*/__this.ret+='" required>';
__this.line=34;__this.ret+='\n        </div>';
__this.line=35;__this.ret+='\n        ';
__this.line=36;__this.ret+='\n        <div class="diary-form-group">';
__this.line=37;__this.ret+='\n            <label for="body">本文:</label>';
__this.line=38;__this.ret+='\n            <textarea id="body" name="body" required placeholder="今日の出来事を書いてください...">';/*=*/__this.ret+=__this.escapeHTML( body || '' );/*+*/__this.ret+='</textarea>';
__this.line=39;__this.ret+='\n        </div>';
__this.line=40;__this.ret+='\n        ';
__this.line=41;__this.ret+='\n        <div class="diary-form-buttons">';
__this.line=42;__this.ret+='\n            <button type="submit">';/*=*/__this.ret+=__this.escapeHTML( isEdit ? '更新' : '投稿' );/*+*/__this.ret+='</button>';
__this.line=43;__this.ret+='\n            <button type="button" onclick="history.back()">キャンセル</button>';
__this.line=44;__this.ret+='\n            ';/* */ if (isEdit && entry) { ;/*+*/__this.ret+='';
__this.line=45;__this.ret+='\n                <button type="button" onclick="handleDelete(\'';/*=*/__this.ret+=__this.escapeHTML( entry.id );/*+*/__this.ret+='\')" style="background-color:#dc3545;color:white;border:1px solid #dc3545;">削除</button>';
__this.line=46;__this.ret+='\n            ';/* */ } ;/*+*/__this.ret+='';
__this.line=47;__this.ret+='\n        </div>';
__this.line=48;__this.ret+='\n        ';
__this.line=49;__this.ret+='\n        <input type="hidden" name="x-requested-with" value="XMLHttpRequest">';
__this.line=50;__this.ret+='\n    </form>';
__this.line=51;__this.ret+='\n';
__this.line=52;__this.ret+='\n    <script>';
__this.line=53;__this.ret+='\n        // CSRFトークン代わりにx-requested-withヘッダーを送信';
__this.line=54;__this.ret+='\n        document.querySelector(\'form\').addEventListener(\'submit\', function(e) {';
__this.line=55;__this.ret+='\n            e.preventDefault();';
__this.line=56;__this.ret+='\n            ';
__this.line=57;__this.ret+='\n            const formData = new FormData(this);';
__this.line=58;__this.ret+='\n            ';
__this.line=59;__this.ret+='\n            fetch(this.action, {';
__this.line=60;__this.ret+='\n                method: \'POST\',';
__this.line=61;__this.ret+='\n                headers: {';
__this.line=62;__this.ret+='\n                    \'x-requested-with\': \'XMLHttpRequest\'';
__this.line=63;__this.ret+='\n                },';
__this.line=64;__this.ret+='\n                body: formData';
__this.line=65;__this.ret+='\n            })';
__this.line=66;__this.ret+='\n            .then(response => {';
__this.line=67;__this.ret+='\n                if (response.ok || response.status === 302) {';
__this.line=68;__this.ret+='\n                    // 成功時は詳細ページにリダイレクト（レスポンスからURLを取得）';
__this.line=69;__this.ret+='\n                    return response.text().then(text => {';
__this.line=70;__this.ret+='\n                        if (text.startsWith(\'/diary/\')) {';
__this.line=71;__this.ret+='\n                            window.location.href = text;';
__this.line=72;__this.ret+='\n                        } else {';
__this.line=73;__this.ret+='\n                            // HTMLレスポンスの場合は表示';
__this.line=74;__this.ret+='\n                            document.open();';
__this.line=75;__this.ret+='\n                            document.write(text);';
__this.line=76;__this.ret+='\n                            document.close();';
__this.line=77;__this.ret+='\n                        }';
__this.line=78;__this.ret+='\n                    });';
__this.line=79;__this.ret+='\n                } else {';
__this.line=80;__this.ret+='\n                    // エラーの場合はHTMLを表示';
__this.line=81;__this.ret+='\n                    return response.text().then(text => {';
__this.line=82;__this.ret+='\n                        document.open();';
__this.line=83;__this.ret+='\n                        document.write(text);';
__this.line=84;__this.ret+='\n                        document.close();';
__this.line=85;__this.ret+='\n                    });';
__this.line=86;__this.ret+='\n                }';
__this.line=87;__this.ret+='\n            })';
__this.line=88;__this.ret+='\n            .catch(() => {';
__this.line=89;__this.ret+='\n                alert(\'送信に失敗しました。\');';
__this.line=90;__this.ret+='\n            });';
__this.line=91;__this.ret+='\n        });';
__this.line=92;__this.ret+='\n';
__this.line=93;__this.ret+='\n        function handleDelete(entryId) {';
__this.line=94;__this.ret+='\n            if (!confirm(\'本当に削除しますか？\')) {';
__this.line=95;__this.ret+='\n                return;';
__this.line=96;__this.ret+='\n            }';
__this.line=97;__this.ret+='\n            ';
__this.line=98;__this.ret+='\n            fetch(`/diary/${entryId}/delete`, {';
__this.line=99;__this.ret+='\n                method: \'POST\',';
__this.line=100;__this.ret+='\n                headers: {';
__this.line=101;__this.ret+='\n                    \'x-requested-with\': \'XMLHttpRequest\'';
__this.line=102;__this.ret+='\n                }';
__this.line=103;__this.ret+='\n            })';
__this.line=104;__this.ret+='\n            .then(response => {';
__this.line=105;__this.ret+='\n                if (response.ok || response.status === 302) {';
__this.line=106;__this.ret+='\n                    // 削除成功時は日記一覧にリダイレクト';
__this.line=107;__this.ret+='\n                    window.location.href = \'/diary\';';
__this.line=108;__this.ret+='\n                } else {';
__this.line=109;__this.ret+='\n                    alert(\'削除に失敗しました。\');';
__this.line=110;__this.ret+='\n                }';
__this.line=111;__this.ret+='\n            })';
__this.line=112;__this.ret+='\n            .catch(() => {';
__this.line=113;__this.ret+='\n                alert(\'削除に失敗しました。\');';
__this.line=114;__this.ret+='\n            });';
__this.line=115;__this.ret+='\n        }';
__this.line=116;__this.ret+='\n    </script>';
__this.line=117;__this.ret+='\n';/* */ }); /* end of wrapper */ ;/*end*/ return __this.ret;} catch (e) { throw new Error('TemplateError: '+e+' (on diary/form line ' + __this.line + ')',{cause:e}); }

};
compiled['diary/form'].keys = ["body","date","entry","error","include","isEdit","title","wrapper"];
compiled['diary/list'] = function anonymous(__this,entries,formatDateForDisplay,formatDateOnly,include,nl2br,title,wrapper,years
) {
try {/*+*/__this.ret+='<!--meta.keys=["title", "entries", "years", "formatDateOnly", "formatDateForDisplay", "nl2br"]-->';
__this.line=2;__this.ret+='\n';/* */ __this.stash.title = '日記'; ;/*+*/__this.ret+='';
__this.line=3;__this.ret+='\n';/* */ wrapper('wrapper', () => { ;/*+*/__this.ret+='';
__this.line=4;__this.ret+='\n    <style>';
__this.line=5;__this.ret+='\n        .diary-nav { margin: 20px 0; }';
__this.line=6;__this.ret+='\n        .diary-nav a { margin-right: 15px; color: #0066cc; text-decoration: none; }';
__this.line=7;__this.ret+='\n        .diary-nav a:hover { text-decoration: underline; }';
__this.line=8;__this.ret+='\n        .diary-entry { margin-bottom: 30px; border-bottom: 1px dotted #ccc; padding-bottom: 20px; }';
__this.line=9;__this.ret+='\n        .diary-entry-date { font-weight: bold; color: #333; margin-bottom: 10px; }';
__this.line=10;__this.ret+='\n        .diary-entry-date a { color: #333; text-decoration: none; }';
__this.line=11;__this.ret+='\n        .diary-entry-date a:hover { text-decoration: underline; }';
__this.line=12;__this.ret+='\n        .diary-entry-body { white-space: pre-wrap; line-height: 1.6; }';
__this.line=13;__this.ret+='\n        .diary-entry-meta { font-size: 0.9em; color: #666; margin-top: 10px; }';
__this.line=14;__this.ret+='\n        .diary-admin-links { margin-top: 10px; }';
__this.line=15;__this.ret+='\n        .diary-admin-links a { margin-right: 10px; font-size: 0.9em; color: #0066cc; }';
__this.line=16;__this.ret+='\n        .diary-no-entries { text-align: center; color: #999; margin: 40px 0; }';
__this.line=17;__this.ret+='\n    </style>';
__this.line=18;__this.ret+='\n';
__this.line=19;__this.ret+='\n    <h1><a href="/diary">日記</a></h1>';
__this.line=20;__this.ret+='\n    ';
__this.line=21;__this.ret+='\n    <div class="diary-nav">';
__this.line=22;__this.ret+='\n        <a href="/diary">最新</a>';
__this.line=23;__this.ret+='\n        ';/* */ if (years && years.length > 0) { ;/*+*/__this.ret+='';
__this.line=24;__this.ret+='\n            ';/* */ years.forEach(function(year) { ;/*+*/__this.ret+='';
__this.line=25;__this.ret+='\n                <a href="/diary/year/';/*=*/__this.ret+=__this.escapeHTML( year );/*+*/__this.ret+='">';/*=*/__this.ret+=__this.escapeHTML( year );/*+*/__this.ret+='年</a>';
__this.line=26;__this.ret+='\n            ';/* */ }); ;/*+*/__this.ret+='';
__this.line=27;__this.ret+='\n        ';/* */ } ;/*+*/__this.ret+='';
__this.line=28;__this.ret+='\n        <a href="/diary/new">新規投稿</a>';
__this.line=29;__this.ret+='\n    </div>';
__this.line=30;__this.ret+='\n';
__this.line=31;__this.ret+='\n    ';/* */ if (entries && entries.length > 0) { ;/*+*/__this.ret+='';
__this.line=32;__this.ret+='\n        ';/* */ entries.forEach(function(entry) { ;/*+*/__this.ret+='';
__this.line=33;__this.ret+='\n            <div class="diary-entry">';
__this.line=34;__this.ret+='\n                <div class="diary-entry-date">';
__this.line=35;__this.ret+='\n                    <a href="/diary/';/*=*/__this.ret+=__this.escapeHTML( entry.id );/*+*/__this.ret+='">';/*=*/__this.ret+=__this.escapeHTML( formatDateOnly(entry.id) );/*+*/__this.ret+='</a>';
__this.line=36;__this.ret+='\n                </div>';
__this.line=37;__this.ret+='\n                <div class="diary-entry-body">';/*raw*/__this.ret+=( nl2br(entry.body) );/*+*/__this.ret+='</div>';
__this.line=38;__this.ret+='\n                <div class="diary-entry-meta">';
__this.line=39;__this.ret+='\n                    作成: ';/*=*/__this.ret+=__this.escapeHTML( formatDateForDisplay(entry.createdAt) );/*+*/__this.ret+='';
__this.line=40;__this.ret+='\n                    ';/* */ if (entry.updatedAt !== entry.createdAt) { ;/*+*/__this.ret+='';
__this.line=41;__this.ret+='\n                        / 更新: ';/*=*/__this.ret+=__this.escapeHTML( formatDateForDisplay(entry.updatedAt) );/*+*/__this.ret+='';
__this.line=42;__this.ret+='\n                    ';/* */ } ;/*+*/__this.ret+='';
__this.line=43;__this.ret+='\n                </div>';
__this.line=44;__this.ret+='\n            </div>';
__this.line=45;__this.ret+='\n        ';/* */ }); ;/*+*/__this.ret+='';
__this.line=46;__this.ret+='\n    ';/* */ } else { ;/*+*/__this.ret+='';
__this.line=47;__this.ret+='\n        <div class="diary-no-entries">日記がまだありません。</div>';
__this.line=48;__this.ret+='\n    ';/* */ } ;/*+*/__this.ret+='';
__this.line=49;__this.ret+='\n';/* */ }); /* end of wrapper */ ;/*end*/ return __this.ret;} catch (e) { throw new Error('TemplateError: '+e+' (on diary/list line ' + __this.line + ')',{cause:e}); }

};
compiled['diary/list'].keys = ["entries","formatDateForDisplay","formatDateOnly","include","nl2br","title","wrapper","years"];
const regexp = /[<>"'&]/;
const escapeHTML = function (str) {
		if (typeof str !== 'string') str = String(str);
		let match = regexp.exec(str);
		if (match === null) return str;
		let result = str.slice(0, match.index);
		for (let i = match.index, len = str.length; i < len; i++) {
			switch (str.charCodeAt(i)) {
				case 60: result += '&lt;'; break; // <
				case 62: result += '&gt;'; break; // >
				case 34: result += '&#x22;'; break; // "
				case 39: result += '&#x27;'; break; // '
				case 38: result += '&amp;'; break; // &
				default: result += str[i]; break;
			}
		}
		return result;
	};
const template = function (id, stash) {
		const me = template;
		const func = compiled[id];
		if (!func) {
			throw new Error(`Template "${id}" not found.`);
		}
		return func.call(null, me.context = { escapeHTML, line: 1, ret: '', stash }, ...func.keys.map(key => stash[key]));
	};
const extended = function extended (id, data) {
	const inject = {
		include : function (name, args) {
			const stash =  Object.assign({}, template.context.stash, args);
			const context = template.context;
			context.ret += template(name, stash);
			template.context = context;
		},

		wrapper : function (name, fun) {
			const current = template.context.ret;
			template.context.ret = '';
			fun.apply(template.context);
			const content = template.context.ret;
			const orig_content = template.context.stash.content;
			template.context.stash.content = content;
			template.context.ret = current + template(name, template.context.stash);
			template.context.stash.content = orig_content;
		},
	}
	return template(id, Array.isArray(data) ? Object.keys(inject).concat(data) : Object.assign({}, data, inject));
};
export { template, extended };
